[metadata]
name = sniffcell
version = 0.9.7
author = Yilei Fu
author_email = yilei.fu@bcm.edu
description = SniffCell annotates structural variants using long-read methylation evidence and ctDMR signals.
long_description = file: README.md
long_description_content_type = text/markdown
url = https://github.com/Fu-Yilei/SniffCell
license = Apache-2.0
project_urls =
    Bug Tracker = https://github.com/Fu-Yilei/SniffCell/issues
classifiers =
    Programming Language :: Python :: 3
    License :: OSI Approved :: Apache Software License
    Operating System :: OS Independent

[options]
package_dir =
    = src
packages = find:
python_requires = >=3.10
install_requires =
    pysam>=0.21.0
    numpy>=2.2.0
    pandas>=2.3.0
    scipy
    tqdm
    scikit-learn
    matplotlib
include_package_data = True

[options.packages.find]
where = src

[options.entry_points]
console_scripts =
    sniffcell = sniffcell.main:main
    sniffcell-discover-sv = sniffcell.sv_discovery:main
    sniffcell-check-discover = sniffcell.discover.envcheck:main

[options.extras_require]
discover =
    tdb
    seaborn>=0.13
discover-plots =
    seaborn>=0.13
igvreport =
    igv-reports
full =
    tdb
    seaborn>=0.13
    igv-reports
