#!/usr/bin/env python
import sys, os

import src.deconv.deconv_argparse
import src.deconv.deconv_main

sys.path.append(os.path.join(os.path.dirname(__file__), 'src'))
sys.path.append(os.path.join(os.path.dirname(__file__), 'src/deconv'))

if __name__ == "__main__":
    src.deconv.deconv_main.main(sys.argv[1:])